// CLIENT PARAMS

#define MAX_USERNAME_LENGTH 15 
#define MAX_PASSWORD_LENGTH 15 
#define MIN_PASSWORD_LENGTH 8
#define MAX_FILE_SIZE (1L << 30) // 1GB
#define PORT 8080

#define N_ACK "NCK"
#define ACK "ACK"


#define OK 1

// Error codes
#define SOCKET_INIT_ERROR -1
#define INVALID_ADDRESS_ERROR -2

#define CONNECTION_ERROR -4
#define SOCKET_READ_ERROR -10
#define SOCKET_WRITE_ERROR -11
#define SOCKET_CLOSE_ERROR -12
#define BIO_INIT_ERROR -13

#define PRIVATE_KEY_READ_ERROR -20
#define PUBLIC_KEY_READ_ERROR -21
#define PUBLIC_KEY_EXTRACTION_ERROR -22
#define EVP_VERIFY_INIT_ERROR -23
#define EVP_VERIFY_UPDATE_ERROR -24
#define EVP_VERIFY_FINALIZATION_ERROR -25

#define DH_PARAM_READ_ERROR -30
#define DH_CTX_INIT_ERROR -31
#define EVP_PKEY_KEYGEN_INIT_ERROR -32
#define EVP_PKEY_KEYGEN_ERROR -33
#define DH_PUBKEY_SEND_ERROR -34
#define EVP_PKEY_CTX_CREATION_ERROR -35
#define EVP_PKEY_DERIVATION_ERROR -36
#define EVP_PKEY_SECRET_DERIVATION_ERROR -37
#define SIGNATURE_VERIFICATION_ERROR -38

#define EVP_CIPHER_CTX_CREATION_ERROR -40
#define EVP_CIPHER_CTX_INIT_ERROR -41
#define EVP_CIPHER_CTX_IV_SET_ERROR -42
#define EVP_CIPHER_CTX_UPDATE_ERROR -43
#define EVP_CIPHER_CTX_FINALIZATION_ERROR -44
#define EVP_CIPHER_CTX_TAG_RETRIEVAL_ERROR -45
#define EVP_PKEY_CTX_DECRYPTION_ERROR -46

#define ENCRYPTION_ERROR -50

#define DECRYPTION_ERROR -60

#define BAD_USERNAME -100
#define BAD_PASSWORD -101
#define BAD_PW_UPDATE -102
#define MALLOC_ERROR -103

#define PUBKEY_RECEIVAL_ERROR -110
#define FILE_OPEN_ERROR -111
#define FILE_WRITE_ERROR -112
#define FILE_READ_ERROR -113

#define FILE_TOO_BIG -120
#define HASH_ERROR -121
#define SIGNATURE_GEN_ERROR -122
#define SIGNATURE_FILE_SAVE_ERROR -123

#define NONCE_GENERATION_ERROR -200
