#define MAX_USERNAME_LENGTH 15
#define MIN_PASSWORD_LENGTH 8  
#define MAX_PASSWORD_LENGTH 15 
#define SALT_LEN 32 
#define PORT 8080


#define KEY_SIZE 3072
#define PUB_EXP  17
#define BASE_DIRECTORY "./UsersKeys/"
#define PRIVATE_KEY_FILE_FORMAT BASE_DIRECTORY "%s_private_key.pem"
#define PUBLIC_KEY_FILE_FORMAT BASE_DIRECTORY "%s_public_key.pem"


#define N_ACK "NCK"
#define ACK "ACK"


#define OK 1

// Error codes
#define SOCKET_INIT_ERROR -1

#define SOCKET_BIND_ERROR -3
#define SOCKET_LISTEN_ERROR -4
#define SOCKET_READ_ERROR -10
#define SOCKET_WRITE_ERROR -11
#define SOCKET_CLOSE_ERROR -12
#define BIO_INIT_ERROR -13

#define PRIVATE_KEY_READ_ERROR -20
#define PRIVATE_KEY_EXTRACTION_ERROR -21
#define SIGNING_CONTEXT_INIT_ERROR -22
#define SIGNING_CONTEXT_UPDATE_ERROR -23
#define SIGNATURE_FINALIZATION_ERROR -24
#define NOT_HASHED_INPUT_ERROR -25
#define PASSKEY_READ_ERROR -26

#define DH_PARAM_READ_ERROR -30
#define DH_CTX_INIT_ERROR -31
#define EVP_PKEY_KEYGEN_INIT_ERROR -32
#define EVP_PKEY_KEYGEN_ERROR -33
#define DH_PUBKEY_SEND_ERROR -34
#define EVP_PKEY_CTX_CREATION_ERROR -35
#define EVP_PKEY_DERIVATION_ERROR -36
#define EVP_PKEY_SECRET_DERIVATION_ERROR -37

#define EVP_CIPHER_CTX_CREATION_ERROR -40
#define EVP_CIPHER_CTX_INIT_ERROR -41
#define EVP_CIPHER_CTX_IV_SET_ERROR -42
#define EVP_CIPHER_CTX_UPDATE_ERROR -43
#define EVP_CIPHER_CTX_FINALIZATION_ERROR -44
#define EVP_CIPHER_CTX_TAG_RETRIEVAL_ERROR -45
#define EVP_PKEY_CTX_DECRYPTION_ERROR -46

#define ENCRYPTION_ERROR -50

#define DECRYPTION_ERROR -60

#define BAD_HASH -70

#define KEY_DELETE_ERROR -80

#define USER_PUBKEY_READ_ERROR -90

#define BAD_USERNAME -100
#define BAD_PASSWORD -101
#define MALLOC_ERROR -102

#define PWD_FILE_OPEN_ERROR -110
#define MALFORMED_USERNAME_LINE_ERROR -111

#define BAD_FILE_FORMAT -120

#define UNKNOWN_OPERATION_ERROR -130

#define USER_KEYGEN_ERROR -140

#define NONCE_GENERATION_ERROR -200
